import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

// Security headers are defined here once and emitted two ways:
//   * a <meta http-equiv="Content-Security-Policy"> in the built index.html,
//     for static hosts that serve no custom headers;
//   * a `_headers` file in the build output, which Cloudflare Pages and
//     Netlify turn into real HTTP response headers.
// Generating both from the same constants keeps them from drifting apart.
//
// The CSP is applied to production builds only. Vite's dev server needs inline
// scripts for the React Fast Refresh preamble, which `script-src 'self'` would
// block, so applying it in dev breaks `npm run dev`.

function buildCsp(proxyEnabled) {
  return [
    "default-src 'self'",
    "script-src 'self'",
    // React `style={{...}}` props and the inline styles Chart.js sets on its canvas.
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob:",
    "font-src 'self'",
    // With the proxy transport compiled in, the user types an arbitrary LAN
    // host that the app reaches over http:// and ws://, so this has to stay
    // open. The deploy build drops that transport, which lets the directive
    // lock down to 'self'.
    proxyEnabled ? "connect-src 'self' http: https: ws: wss:" : "connect-src 'self'",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-src 'none'",
    "worker-src 'self' blob:",
    "manifest-src 'self'",
  ];
}

// frame-ancestors is ignored when delivered in a <meta> tag, so it goes into
// the HTTP header only.
const FRAME_ANCESTORS = "frame-ancestors 'none'";

// The WebSocket transport module, dynamically imported by ConnectionDialog and
// stripped from the deploy build.
const PROXY_MODULE = 'kinisi_ws_client';

function headersFile(proxyEnabled) {
  const csp = [...buildCsp(proxyEnabled), FRAME_ANCESTORS].join('; ');
  return `# Generated by vite.config.js at build time - do not edit by hand.
# Static hosts that read a \`_headers\` file (Cloudflare Pages, Netlify) turn
# these into real HTTP response headers. On hosts that ignore the file it is
# inert, and the <meta http-equiv="Content-Security-Policy"> in index.html
# still applies the same policy (minus frame-ancestors, which browsers ignore
# in meta form).
#
# Proxy (WebSocket) transport: ${proxyEnabled ? 'enabled' : 'disabled'}

/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  Referrer-Policy: no-referrer
  Cross-Origin-Opener-Policy: same-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()
`;
}

function securityHeaders(proxyEnabled, outDir) {
  return {
    name: 'security-headers',
    apply: 'build',
    transformIndexHtml(html) {
      return {
        html,
        tags: [
          {
            tag: 'meta',
            attrs: {
              'http-equiv': 'Content-Security-Policy',
              content: buildCsp(proxyEnabled).join('; '),
            },
            injectTo: 'head-prepend',
          },
        ],
      };
    },
    closeBundle() {
      writeFileSync(resolve(outDir, '_headers'), headersFile(proxyEnabled));
    },
    generateBundle(_options, bundle) {
      if (proxyEnabled) return;
      // Tree-shaking removes the only call site of the `import()` in
      // ConnectionDialog, but the bundler still emits a chunk for it, leaving
      // an orphan file that nothing references. Drop it so the deployed build
      // really does ship without the proxy transport.
      for (const [fileName, chunk] of Object.entries(bundle)) {
        if (chunk.type !== 'chunk') continue;
        const id = chunk.facadeModuleId || '';
        if (chunk.name === PROXY_MODULE || id.includes(PROXY_MODULE)) {
          delete bundle[fileName];
        }
      }
    },
  };
}

export default defineConfig(({ mode }) => {
  // '' loads every variable rather than only the VITE_-prefixed ones, which is
  // what we want for reading the flag out of .env.<mode>.
  const env = loadEnv(mode, process.cwd(), '');
  // Enabled unless explicitly turned off, so `npm run dev` and a plain
  // `npm run build` keep both transports. `npm run build:deploy` reads
  // .env.deploy to switch it off. See src/config.js.
  const proxyEnabled = env.VITE_ENABLE_PROXY !== 'false';
  // Keep CRA's output directory so existing deploy configuration keeps working.
  const outDir = 'build';

  return {
    plugins: [react(), securityHeaders(proxyEnabled, outDir)],
    build: {
      outDir,
      // Emit every script as an external file. An inline module would require
      // `script-src 'unsafe-inline'`, defeating the policy above.
      assetsInlineLimit: 0,
    },
    server: { port: 3000 },
    preview: { port: 3000 },
    test: {
      environment: 'jsdom',
      globals: true,
      setupFiles: './src/setupTests.js',
      css: true,
    },
  };
});
