import { INITIALIZE_MOTOR_POSITION_CONTROLLER, RESET_MOTOR_POSITION, SET_MOTOR_POSITION,
  GET_MOTOR_POSITION, INITIALIZE_PLATFORM_POSITION_CONTROLLER, RESET_PLATFORM_POSITION,
  SET_PLATFORM_POSITION, INITIALIZE_MOTOR_POSITION_PID_CONTROLLER,
  INITIALIZE_PLATFORM_POSITION_PID_CONTROLLER } from './kinisi_commands.js';

export const POSITION_PID_COMMANDS = new Set([INITIALIZE_MOTOR_POSITION_PID_CONTROLLER,
  INITIALIZE_PLATFORM_POSITION_PID_CONTROLLER]);

export function supportsPositionPidControl(info) {
  return info?.protocol_major === 2 && info.protocol_minor >= 3;
}

export const POSITION_COMMANDS = new Set([INITIALIZE_MOTOR_POSITION_CONTROLLER,
  RESET_MOTOR_POSITION, SET_MOTOR_POSITION, GET_MOTOR_POSITION,
  INITIALIZE_PLATFORM_POSITION_CONTROLLER, RESET_PLATFORM_POSITION, SET_PLATFORM_POSITION]);

export function supportsPositionControl(info) {
  return info?.protocol_major === 2 && info.protocol_minor >= 2;
}
